# Generated by Django 4.1.2 on 2023-02-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default=None, upload_to='profile_pic/'),
        ),
    ]
