# Generated by Django 4.1.2 on 2023-02-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_special_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('mobile', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('block', models.CharField(max_length=50)),
                ('house', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='profile_pic/')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
