# Generated by Django 4.1.2 on 2023-02-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_society_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='society_member',
            name='member_type',
            field=models.CharField(default='house_owner', max_length=100),
        ),
    ]
