# Generated by Django 4.1.2 on 2023-02-07 17:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_event_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('person', models.PositiveIntegerField()),
                ('mobile', models.PositiveBigIntegerField()),
                ('vehicle_no', models.CharField(default=None, max_length=100)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.society_member')),
            ],
        ),
    ]
